export const LOAD_BRANCH = 'LOAD_BRANCH';
export const LOAD_BRANCH_SUCCESS = 'LOAD_BRANCH_SUCCESS';
export const SWITCH_BRANCH = 'SWITCH_BRANCH';
export const SHOW_CREATE_BRANCH = 'SHOW_CREATE_BRANCH';
export const CREATE_BRANCH = 'CREATE_BRANCH';
export const CREATE_BRANCH_SUCCESS = 'CREATE_BRANCH_SUCCESS';
export const CLOSE_BRANCH_DIALOG = 'CLOSE_BRANCH_DIALOG';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';

export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export const LOAD_CUSTOMER_ITEMS = 'LOAD_CUSTOMER_ITEMS';
export const LOAD_CUSTOMER_ITEMS_SUCCESS = 'LOAD_CUSTOMER_ITEMS_SUCCESS';
export const CREATE_CUSTOMER_ITEMS = 'CREATE_CUSTOMER_ITEMS';
export const CREATE_CUSTOMER_ITEMS_SUCCESS = 'CREATE_CUSTOMER_ITEMS_SUCCESS';
export const UPDATE_CUSTOMER_ITEMS = 'UPDATE_CUSTOMER_ITEMS';
export const UPDATE_CUSTOMER_ITEMS_SUCCESS = 'UPDATE_CUSTOMER_ITEMS_SUCCESS';

export const LOAD_PURCHASE_ORDER = 'LOAD_PURCHASE_ORDER';
export const LOAD_PURCHASE_ORDER_SUCCESS = 'LOAD_PURCHASE_ORDER_SUCCESS';
export const CREATE_PURCHASE_ORDER = 'CREATE_PURCHASE_ORDER';
export const CREATE_PURCHASE_ORDER_SUCCESS = 'CREATE_PURCHASE_ORDER_SUCCESS';
export const UPDATE_PURCHASE_ORDER = 'UPDATE_PURCHASE_ORDER';
export const UPDATE_PURCHASE_ORDER_SUCCESS = 'UPDATE_PURCHASE_ORDER_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const CREATE_USERS = 'CREATE_USERS';