export const LOAD_BRANCH = 'LOAD_BRANCH';
export const CHANGE_BRANCH = 'CHANGE_BRANCH';
export const CREATE_BRANCH = 'CREATE_BRANCH';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';

export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export const LOAD_CUSTOMER_ITEMS = 'LOAD_CUSTOMER_ITEMS';
export const LOAD_CUSTOMER_ITEMS_SUCCESS = 'LOAD_CUSTOMER_ITEMS_SUCCESS';
export const CREATE_CUSTOMER_ITEMS = 'CREATE_CUSTOMER_ITEMS';
export const CREATE_CUSTOMER_ITEMS_SUCCESS = 'CREATE_CUSTOMER_ITEMS_SUCCESS';
export const UPDATE_CUSTOMER_ITEMS = 'UPDATE_CUSTOMER_ITEMS';
export const UPDATE_CUSTOMER_ITEMS_SUCCESS = 'UPDATE_CUSTOMER_ITEMS_SUCCESS';